### ISSUE TITLE
Removing dependency on make for installation

### ISSUE THREAD

**Issue by stephengroat** [robzr/bearDropper#1]
First, let me say that I love the utility, great work!

Since this is designed for OpenWRT, and since `make` isn't easily available in OpenWRT (either as part of busybox or as a package), I was wondering what you thought about maybe just scripting up install outside of `make`?

**Comment by robzr** [comment]
Hi Stephen - will do, the make was kind of a legacy thing anyways.  I'll post some install instructions that don't require make.  Thanks for the feedback,

Rob
