### ISSUE TITLE
Persistent database is not restored

### ISSUE THREAD

**Issue by ldir-EDB0** [robzr/bearDropper#2]
Hi Rob,

Encountering a bug on reboot of a system where the persistent database is not being restored.  loadState () calls bddbLoad twice with the persistent & temp filenames, unfortunately bddbLoad itself calls bddbClear.  So right after loading the persistent database into the environment, the call to load the temporary database removes all the stuff we've just loaded.

I'm guessing the solution is to call bddbClear at the top of 'loadState' and not call it from bddbLoad.

Kevin

**Comment by robzr** [comment]
Hey Kevin - I appreciate the work troubleshooting that, good catch.

I moved bddbClear out of bddbLoad and put it at the beginning of loadState, before the persistent bddbLoad (exactly as you suggested).  This should be a pretty straightforward change but I'm going to leave this open until I do some testing - if you do any testing please let me know what you find.  Thanks,

Rob

**Comment by ldir-EDB0** [comment]
On 09/05/16 23:17, Rob Zwissler wrote:

> Hey Kevin - I appreciate the work troubleshooting that, good catch.
> 
> I moved bddbClear out of bddbLoad and put it at the beginning of
> loadState, before the persistent bddbLoad. This should be a pretty
> straightforward change but I'm going to leave this open until I do
> some testing - if you do any testing please let me know what you find.
> 
> Looks and runs good for me :-)

Kevin

**Comment by robzr** [comment]
Killer - thanks Kevin.
